// <auto-generated />
using System;
using ContestSystem.Models.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContestSystem.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20210811184039_Deleting ulong PKs pt 1")]
    partial class DeletingulongPKspt1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ContestSystem.DbStructure.Models.Checker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<long?>("ApprovingModeratorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("AuthorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompilationVerdict")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Errors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchieved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("ModerationMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ApprovingModeratorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Checkers");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.CheckerServer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastTimeCompilersUpdatedUTC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastTimeUsedForSolutionUTC")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("CheckerServers");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.CheckerServerCompiler", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CheckerServerId")
                        .HasColumnType("bigint");

                    b.Property<string>("CompilerGUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompilerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("CheckerServerId");

                    b.ToTable("CheckerServersCompilers");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.Contest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<long?>("ApprovingModeratorId")
                        .HasColumnType("bigint");

                    b.Property<bool>("AreVirtualContestsAvailable")
                        .HasColumnType("bit");

                    b.Property<long?>("CreatorId")
                        .HasColumnType("bigint");

                    b.Property<short>("DurationInMinutes")
                        .HasColumnType("smallint");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("ModerationMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RulesSetId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDateTimeUTC")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ApprovingModeratorId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("RulesSetId");

                    b.ToTable("Contests");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.ContestFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ContestId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ContestId");

                    b.ToTable("ContestsFiles");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.ContestLocalModerator", b =>
                {
                    b.Property<long>("ContestId")
                        .HasColumnType("bigint");

                    b.Property<long>("LocalModeratorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("ContestId", "LocalModeratorId")
                        .HasName("PK_ContestsLocalModerators")
                        .IsClustered();

                    b.HasIndex("ContestId");

                    b.HasIndex("LocalModeratorId");

                    b.ToTable("ContestsLocalModerators");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.ContestLocalizer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ContestId")
                        .HasColumnType("bigint");

                    b.Property<string>("Culture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ContestId");

                    b.ToTable("ContestsLocalizers");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.ContestParticipant", b =>
                {
                    b.Property<long>("ContestId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParticipantId")
                        .HasColumnType("bigint");

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ConfirmedByLocalModerator")
                        .HasColumnType("bit");

                    b.Property<bool>("ConfirmedByParticipant")
                        .HasColumnType("bit");

                    b.Property<long?>("ConfirmingLocalModeratorId")
                        .HasColumnType("bigint");

                    b.Property<long>("Result")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("ContestId", "ParticipantId")
                        .HasName("PK_ContestsParticipants")
                        .IsClustered();

                    b.HasIndex("ConfirmingLocalModeratorId");

                    b.HasIndex("ContestId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("ContestsParticipants");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.ContestProblem", b =>
                {
                    b.Property<long>("ContestId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProblemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Letter")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("ContestId", "ProblemId")
                        .HasName("PK_ContestsProblems")
                        .IsClustered();

                    b.HasIndex("ContestId");

                    b.HasIndex("ProblemId");

                    b.ToTable("ContestsProblems");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.Course", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<long?>("ApprovingModeratorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("ModerationMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ApprovingModeratorId");

                    b.HasIndex("CreatorId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.CourseLocalModerator", b =>
                {
                    b.Property<long>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<long>("LocalModeratorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("CourseId", "LocalModeratorId")
                        .HasName("PK_CoursesLocalModerators")
                        .IsClustered();

                    b.HasIndex("CourseId");

                    b.HasIndex("LocalModeratorId");

                    b.ToTable("CoursesLocalModerators");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.CourseLocalizer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<string>("Culture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("CoursesLocalizers");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.CoursePage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CoursePageParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("HtmlText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("CoursePageParentId");

                    b.ToTable("CoursesPages");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.CoursePageFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CoursePageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("CoursePageId");

                    b.ToTable("CoursesPagesFiles");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.CoursePageLocalizer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CoursePageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Culture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtmlText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CoursePageId");

                    b.ToTable("CoursesPagesLocalizers");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.CourseParticipant", b =>
                {
                    b.Property<long>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParticipantId")
                        .HasColumnType("bigint");

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ConfirmedByLocalModerator")
                        .HasColumnType("bit");

                    b.Property<bool>("ConfirmedByParticipant")
                        .HasColumnType("bit");

                    b.Property<long?>("ConfirmingLocalModeratorId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("CourseId", "ParticipantId")
                        .HasName("PK_CoursesParticipants")
                        .IsClustered();

                    b.HasIndex("ConfirmingLocalModeratorId");

                    b.HasIndex("CourseId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("CoursesParticipants");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.CourseProblem", b =>
                {
                    b.Property<long>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProblemId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("CourseId", "ProblemId")
                        .HasName("PK_CoursesProblems")
                        .IsClustered();

                    b.HasIndex("CourseId");

                    b.HasIndex("ProblemId");

                    b.ToTable("CoursesProblems");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.Example", b =>
                {
                    b.Property<long>("ProblemId")
                        .HasColumnType("bigint");

                    b.Property<short>("Number")
                        .HasColumnType("smallint");

                    b.Property<string>("InputText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("ProblemId", "Number")
                        .HasName("PK_Examples")
                        .IsClustered();

                    b.HasIndex("ProblemId");

                    b.ToTable("Examples");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.Post", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<long?>("ApprovingModeratorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("AuthorId")
                        .HasColumnType("bigint");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModerationMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PromotedDateTimeUTC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PublicationDateTimeUTC")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ApprovingModeratorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.PostLocalizer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Culture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtmlText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.Property<string>("PreviewText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("PostsLocalizers");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.Problem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<long?>("ApprovingModeratorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CheckerId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatorId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsArchieved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<long>("MemoryLimitInBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ModerationMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeLimitInMilliseconds")
                        .HasColumnType("int");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ApprovingModeratorId");

                    b.HasIndex("CheckerId");

                    b.HasIndex("CreatorId");

                    b.ToTable("Problems");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.ProblemLocalizer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Culture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InputBlock")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputBlock")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProblemId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ProblemId");

                    b.ToTable("ProblemsLocalizers");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.RulesSet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("AuthorId")
                        .HasColumnType("bigint");

                    b.Property<int>("CountMode")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchieved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<int>("MaxTriesForOneProblem")
                        .HasColumnType("int");

                    b.Property<short>("MonitorFreezeTimeBeforeFinishInMinutes")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PenaltyForCompilationError")
                        .HasColumnType("bit");

                    b.Property<long>("PenaltyForOneMinute")
                        .HasColumnType("bigint");

                    b.Property<long>("PenaltyForOneTry")
                        .HasColumnType("bigint");

                    b.Property<bool>("PointsForBestSolution")
                        .HasColumnType("bit");

                    b.Property<bool>("PublicMonitor")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowFullTestsResults")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("RulesSets");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.Solution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CheckerServerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompilerGUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompilerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ContestId")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorsMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ParticipantId")
                        .HasColumnType("bigint");

                    b.Property<short>("Points")
                        .HasColumnType("smallint");

                    b.Property<long>("ProblemId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SubmitTimeUTC")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Verdict")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CheckerServerId");

                    b.HasIndex("ContestId");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("ProblemId");

                    b.ToTable("Solutions");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.Test", b =>
                {
                    b.Property<long>("ProblemId")
                        .HasColumnType("bigint");

                    b.Property<short>("Number")
                        .HasColumnType("smallint");

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("AvailablePoints")
                        .HasColumnType("smallint");

                    b.Property<string>("Input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("ProblemId", "Number")
                        .HasName("PK_Tests")
                        .IsClustered();

                    b.HasIndex("ProblemId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.TestResult", b =>
                {
                    b.Property<long>("SolutionId")
                        .HasColumnType("bigint");

                    b.Property<short>("Number")
                        .HasColumnType("smallint");

                    b.Property<short>("GotPoints")
                        .HasColumnType("smallint");

                    b.Property<string>("Input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Output")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("UsedMemoryInBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("UsedTimeInMillis")
                        .HasColumnType("int");

                    b.Property<int>("Verdict")
                        .HasColumnType("int");

                    b.HasKey("SolutionId", "Number")
                        .HasName("PK_TestsResults")
                        .IsClustered();

                    b.HasIndex("SolutionId");

                    b.ToTable("TestsResults");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Culture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLimitedInContests")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLimitedInCourses")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLimitedInPosts")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLimitedInProblems")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.VirtualContest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ContestId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParticipantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ContestId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("VirtualContests");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.Checker", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.User", "ApprovingModerator")
                        .WithMany()
                        .HasForeignKey("ApprovingModeratorId");

                    b.HasOne("ContestSystem.DbStructure.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.Navigation("ApprovingModerator");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.CheckerServerCompiler", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.CheckerServer", "CheckerServer")
                        .WithMany("CheckerServerCompilers")
                        .HasForeignKey("CheckerServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckerServer");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.Contest", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.User", "ApprovingModerator")
                        .WithMany()
                        .HasForeignKey("ApprovingModeratorId");

                    b.HasOne("ContestSystem.DbStructure.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.HasOne("ContestSystem.DbStructure.Models.RulesSet", "RulesSet")
                        .WithMany()
                        .HasForeignKey("RulesSetId");

                    b.Navigation("ApprovingModerator");

                    b.Navigation("Creator");

                    b.Navigation("RulesSet");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.ContestFile", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.Contest", "Contest")
                        .WithMany()
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contest");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.ContestLocalModerator", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.Contest", "Contest")
                        .WithMany("ContestLocalModerators")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContestSystem.DbStructure.Models.User", "LocalModerator")
                        .WithMany()
                        .HasForeignKey("LocalModeratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contest");

                    b.Navigation("LocalModerator");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.ContestLocalizer", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.Contest", "Contest")
                        .WithMany("ContestLocalizers")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contest");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.ContestParticipant", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.User", "ConfirmingLocalModerator")
                        .WithMany()
                        .HasForeignKey("ConfirmingLocalModeratorId");

                    b.HasOne("ContestSystem.DbStructure.Models.Contest", "Contest")
                        .WithMany("ContestParticipants")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContestSystem.DbStructure.Models.User", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfirmingLocalModerator");

                    b.Navigation("Contest");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.ContestProblem", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.Contest", "Contest")
                        .WithMany("ContestProblems")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContestSystem.DbStructure.Models.Problem", "Problem")
                        .WithMany("ContestProblems")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contest");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.Course", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.User", "ApprovingModerator")
                        .WithMany()
                        .HasForeignKey("ApprovingModeratorId");

                    b.HasOne("ContestSystem.DbStructure.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.Navigation("ApprovingModerator");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.CourseLocalModerator", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContestSystem.DbStructure.Models.User", "LocalModerator")
                        .WithMany()
                        .HasForeignKey("LocalModeratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("LocalModerator");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.CourseLocalizer", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.CoursePage", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContestSystem.DbStructure.Models.CoursePage", "CoursePageParent")
                        .WithMany()
                        .HasForeignKey("CoursePageParentId");

                    b.Navigation("Course");

                    b.Navigation("CoursePageParent");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.CoursePageFile", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.CoursePage", "CoursePage")
                        .WithMany()
                        .HasForeignKey("CoursePageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoursePage");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.CoursePageLocalizer", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.CoursePage", "CoursePage")
                        .WithMany()
                        .HasForeignKey("CoursePageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoursePage");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.CourseParticipant", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.User", "ConfirmingLocalModerator")
                        .WithMany()
                        .HasForeignKey("ConfirmingLocalModeratorId");

                    b.HasOne("ContestSystem.DbStructure.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContestSystem.DbStructure.Models.User", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfirmingLocalModerator");

                    b.Navigation("Course");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.CourseProblem", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContestSystem.DbStructure.Models.Problem", "Problem")
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.Example", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.Problem", "Problem")
                        .WithMany("Examples")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.Post", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.User", "ApprovingModerator")
                        .WithMany()
                        .HasForeignKey("ApprovingModeratorId");

                    b.HasOne("ContestSystem.DbStructure.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.Navigation("ApprovingModerator");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.PostLocalizer", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.Post", "Post")
                        .WithMany("PostLocalizers")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.Problem", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.User", "ApprovingModerator")
                        .WithMany()
                        .HasForeignKey("ApprovingModeratorId");

                    b.HasOne("ContestSystem.DbStructure.Models.Checker", "Checker")
                        .WithMany()
                        .HasForeignKey("CheckerId");

                    b.HasOne("ContestSystem.DbStructure.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.Navigation("ApprovingModerator");

                    b.Navigation("Checker");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.ProblemLocalizer", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.Problem", "Problem")
                        .WithMany("ProblemLocalizers")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.RulesSet", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.Solution", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.CheckerServer", "CheckerServer")
                        .WithMany("Solutions")
                        .HasForeignKey("CheckerServerId");

                    b.HasOne("ContestSystem.DbStructure.Models.Contest", "Contest")
                        .WithMany()
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContestSystem.DbStructure.Models.User", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId");

                    b.HasOne("ContestSystem.DbStructure.Models.Problem", "Problem")
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckerServer");

                    b.Navigation("Contest");

                    b.Navigation("Participant");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.Test", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.Problem", "Problem")
                        .WithMany("Tests")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.TestResult", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.Solution", "Solution")
                        .WithMany("TestResults")
                        .HasForeignKey("SolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solution");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.VirtualContest", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.Contest", "Contest")
                        .WithMany()
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContestSystem.DbStructure.Models.User", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contest");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContestSystem.DbStructure.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("ContestSystem.DbStructure.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.CheckerServer", b =>
                {
                    b.Navigation("CheckerServerCompilers");

                    b.Navigation("Solutions");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.Contest", b =>
                {
                    b.Navigation("ContestLocalizers");

                    b.Navigation("ContestLocalModerators");

                    b.Navigation("ContestParticipants");

                    b.Navigation("ContestProblems");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.Post", b =>
                {
                    b.Navigation("PostLocalizers");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.Problem", b =>
                {
                    b.Navigation("ContestProblems");

                    b.Navigation("Examples");

                    b.Navigation("ProblemLocalizers");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("ContestSystem.DbStructure.Models.Solution", b =>
                {
                    b.Navigation("TestResults");
                });
#pragma warning restore 612, 618
        }
    }
}
